### ISSUE TITLE
.NET 4.0 support 

### ISSUE THREAD

**Issue by igitur** [thomaslevesque/WeakEvent#1]
Any way to get .NET 4.0 support?

**Comment by thomaslevesque** [comment]
Hi @igitur, 

Yes, I think it should be possible. Currently the library is a PCL that supports .NET Core, which prevents it from also supporting .NET 4.0; but it's possible to create a specific project for 4.0 that uses the same source files. The only issue I can see is that the new reflection API (using `TypeInfo`) is not available in 4.0, but it should be pretty easy to work around.

**Comment by igitur** [comment]
Thanks. 

I'd like to use this code in the https://github.com/amaggiulli/qlnet project to fix our memory leak. QLNet still has .NET4.0 as a dependency, so I can't use the NuGet package, but can I have your permission to use your code (with credit to you) and modify it a bit, e.g. I doubt we need EventArgs, and possibly not even the sender object.

**Comment by thomaslevesque** [comment]
Hi @igitur,

I forgot to add an explicit license, but you can consider the code to be under the Apache 2.0 license, so you can use it as you see fit. I'll try to add proper 4.0 support when I find the time.

**Comment by igitur** [comment]
Great, thanks.

**Comment by thomaslevesque** [comment]
I added the license.

**Comment by thomaslevesque** [comment]
I just released version 2.0, which supports .NET 4.0, .NET 4.5 and .NET Standard 1.1
