### ISSUE TITLE
Support for multiple delegates unsubscription

### ISSUE THREAD

**Issue by Weldryn** [thomaslevesque/WeakEvent#11]
I had a glimpse to the source and it appear `WeakEvent` does not support multiple delegates unsubscription.
Would it be possible to have that?

**Comment by thomaslevesque** [comment]
Hi @Weldryn,

Oops! That's actually a bug. I will fix it ASAP. Thanks for reporting it!

**Comment by thomaslevesque** [comment]
I just published the fix to NuGet. It should be available shortly, after the new package (2.1.1) is validated.

**Comment by Weldryn** [comment]
Wow that was fast! I was ready to offer my help but well... Thanks!

**Comment by Weldryn** [comment]
Wow that was fast! I was ready to offer my help but well... Thanks!
However, do you intended to have the same behaviours regarding delegate operations? ([Combine](https://docs.microsoft.com/en-us/dotnet/api/system.delegate.combine?view=netframework-4.5) and [Remove](https://docs.microsoft.com/en-us/dotnet/api/system.delegate.remove?view=netframework-4.5))

**Comment by thomaslevesque** [comment]
> However, do you intended to have the same behaviours regarding delegate operations? (Combine and Remove)

What do you mean? Are you saying you need methods like these in `WeakEventSource<TEventArgs>`?
```csharp
public void Combine(EventHandler<TEventArgs> handler);
public void Remove(EventHandler<TEventArgs> handler);
```
I'm not sure what the point would be, since they would do the same thing as `Subscribe` and `Unsubscribe`...

**Comment by thomaslevesque** [comment]
> However, Unsubscribe does not comply with Delegate.Remove since it removes all the delegates that match any delegates in handler from _handler, doesn't it?

Yes. Isn't it what `Delegate.Remove` does?

**Comment by Weldryn** [comment]
The documentation for [Remove](https://docs.microsoft.com/en-us/dotnet/api/system.delegate.remove?view=netframework-4.5) states:
> Returns
A new delegate with an invocation list formed by taking the invocation list of source and removing the last occurrence of the invocation list of value, if the invocation list of value is found within the invocation list of source. Returns source if value is null or if the invocation list of value is not found within the invocation list of source. Returns a null reference if the invocation list of value is equal to the invocation list of source or if source is a null reference.

My comprehension is that `Unsubscribe` should only removes the `handler` once, which might be composed of few delegates, if it is found inside `_handlers` by starting searching from the newest.

**Comment by thomaslevesque** [comment]
Ah, I see. I had forgotten about this weird behavior. IMO the `Delegate.Remove` behavior is completely counter-intuitive, and I can't think of a good reason for this design... Is this behavior actually something you rely on?

**Comment by Weldryn** [comment]
Hem not really but because `Delegate` act like that, I would expect 'delegate adapters' like `WeakEventSource` to act the same way. Because delegates are widely used and are at the heart of .Net, I would not be comfortable having a potential sword of Damocles hanging over my head because `WeakEventSource` does not act as I would expected at first.
What are your thought?

**Comment by thomaslevesque** [comment]
> Hem not really but because Delegate act like that, I would expect 'delegate adapters' like WeakEventSource to act the same way. Because delegates are widely used and are at the heart of .Net, I would not be comfortable having a potential sword of Damocles hanging over my head because WeakEventSource does not act as I would expected at first.
> What are your thought?

Well, I never really thought of `WeakEventSource` as a delegate adapter, so I didn't try to mimic the exact same behavior. The methods have different names, and don't claim to do the same thing as `Delegate.Combine`/`Delegate.Remove`.

Also, in my experience, people rarely manipulate multicast delegate except as the backing store for events. i.e., you rarely do `myObject.MyEvent += handler` where `handler` is a multicast delegate. As for the behavior of `Delegate.Remove`, I think most people are not even aware of it; I'd be very surprised if anyone actually relied on it.

So I'm not overly worried about the current behavior; I think it's unlikely that anyone will ever be hurt by it.

That being said, I'm not totally opposed to adopting a behavior that matches `Delegate.Remove` more closely. Would you be interested in working on it?

**Comment by Weldryn** [comment]
> Well, I never really thought of WeakEventSource as a delegate adapter, so I didn't try to mimic the exact same behavior. The methods have different names, and don't claim to do the same thing as Delegate.Combine/Delegate.Remove.
>
> Also, in my experience, people rarely manipulate multicast delegate except as the backing store for events. i.e., you rarely do myObject.MyEvent += handler where handler is a multicast delegate. As for the behavior of Delegate.Remove, I think most people are not even aware of it; I'd be very surprised if anyone actually relied on it.
>
> So I'm not overly worried about the current behavior; I think it's unlikely that anyone will ever be hurt by it.

Fair enough.

> That being said, I'm not totally opposed to adopting a behavior that matches Delegate.Remove more closely. Would you be interested in working on it?

Sure, why not! I need to open my Git book on how to do a clean pull request though...

**Comment by thomaslevesque** [comment]
> Sure, why not! I need to open my Git book on how to do a clean pull request though...

You don't really need to read the book ;)
Here's the short version:

1. fork the repo
2. clone your forked repo on your machine (`git clone <your-repo-url>`)
3. create a new branch from master (`git checkout <branch-name>`)
4. make your changes and commit them on that branch
5. publish the branch (`git push -u origin <branch-name>`)
6. open a PR (GitHub should show a button to do it after you published your branch)

**Comment by thomaslevesque** [comment]
I opened a [new issue](https://github.com/thomaslevesque/WeakEvent/issues/13) to track this.
