### ISSUE TITLE
Raise problem with Multiple subscriptions on the same Event! Raise does not check if an handler still alive

### ISSUE THREAD

**Issue by gigios** [thomaslevesque/WeakEvent#22]
Probably the title is not very clear. I try to explain better.

Yesterday I have seen a deadlock on using the WeakEventSource, I have seen that this problem should be fixed with the last version, and I confirm that the deadlock is solved, BUT, I have a new problem.
This is an easy example that explain my problem (a window with three buttons, one to subscribe custom events, one to unsubscribe, and the last to raise the event):

```csharp
    private readonly WeakEventSource<EventArgs> _evTestSource = new WeakEventSource<EventArgs>();
    public event EventHandler<EventArgs> EventTest
    {
        add { _evTestSource.Subscribe(value); }
        remove { _evTestSource.Unsubscribe(value); }
    }
    
    private void RaiseEventTest()
    {
        _evTestSource?.Raise(this, EventArgs.Empty);
    }
    
    private void Subscribe_Click(object sender, RoutedEventArgs e)
    {
        EventTest += MainWindow_EventTest1;
        EventTest += MainWindow_EventTest2;
    }
    
    private void UnSubscribe_Click(object sender, RoutedEventArgs e)
    {
        EventTest -= MainWindow_EventTest1;
        EventTest -= MainWindow_EventTest2;
    }
    
    private void Raise_Click(object sender, RoutedEventArgs e)
    {
        RaiseEventTest();
    }
    
    private void MainWindow_EventTest1(object sender, EventArgs e)
    {
        Debug.WriteLine("INFO: MainWindow_EventTest1");
        EventTest -= MainWindow_EventTest2;
    }
    
    private void MainWindow_EventTest2(object sender, EventArgs e)
    {
        Debug.WriteLine("INFO: MainWindow_EventTest2");
    }
```
The WeakEvent EventTest is 'attached' with two handlers (MainWindow_EventTest1 and MainWindow_EventTest2).
If I raise the event, by the call of the RaiseEventTest method, the first handler 'theoretically' remove the second handler
```csharp
     EventTest -= MainWindow_EventTest2;
```
But the Raise method of the WeakEventSource raise also the second handler that, theoretically, was removed from the previous handler.
Very hard to explain.
Probably it's necessary to verify, also in the loop used to call the invoke methods, if an handler still active.

**Comment by thomaslevesque** [comment]
Hi @gigios,

This is the intended behavior. Handlers that were alive and subscribed when `Raise` is called are invoked. Unsubscribing when `Raise` is in progress has no effect.

**Comment by gigios** [comment]
Ok! This is also the 'standard' behavior of the normal 'Events'.
My question was to improve the library, for example by a flag to know if an handler still alive checked before call the invoke. Flag that could be 'configurable' via an optional parameter passed in the WeakEventSource constructor (for default disabled to have the same behavior of today).

Anyway, thanks for the reply ;)

**Comment by thomaslevesque** [comment]
Hi @gigios,

I'd rather not implement such a feature. It would be useful to very few people and would introduce significant complexity in the code.
