### ISSUE TITLE
Version 2.0 does not pass Windows App Cert Kit (UWP)

### ISSUE THREAD

**Issue by sonnemaf** [thomaslevesque/WeakEvent#4]
Hi,

I have been using your excellent WeakEvent project using NuGet for a while now. Yesterday I noticed that there is a version 2.0 released. I upgraded my NuGet packaged and released a new version of my UWP app to the Windows Store. This FAILED because of the following report. 

```
Supported API test

FAILED
Supported APIs

**•Error Found: The supported APIs test detected the following errors:◦API FormatMessage in api-ms-win-core-localization-l1-2-0.dll is not supported for this application type. System.Diagnostics.Tracing.dll calls this API.**


•Impact if not fixed:  Using an API that is not part of the Windows SDK for Windows Store apps violates the Windows Store certification requirements. 


•How to fix:  Review the error messages to identify the API that is not part of the Windows SDK for Windows Store apps. Please note, apps that are built in a debug configuration or without .NET Native enabled (where applicable) can fail this test as these environments may pull in unsupported APIs. Retest your app in a release configuration, and with .NET Native enabled if applicable. See the link below for more information: 
 Alternatives to Windows APIs in Windows Store apps. 

```

After downgrading back to the old version it PASSED again. Somewhere you do some calls to System.Diagnostics.Tracing.dll which cause this problem. I hope this report helps.

Thanks

Fons Sonnemans

**Comment by thomaslevesque** [comment]
Hi @sonnemaf,

Thanks for the report. I didn't expect that kind of issue... v2.0.0 targets .NET Standard 1.1, with which UWP is supposed to be compatible.

I never explicitly use System.Diagnostics.Tracing.dll anywhere; I guess it's just pulled automatically as part of `NETStandard.Library`. Maybe I could try to trim down the dependencies to only the packages that are actually needed, but:
- it's not the approach recommended by Microsoft (in fact, there's even an implicit reference to the whole `NETStandard.Library` package in the new SDK-style csproj)
- `System.Diagnostics.Tracing` is used by many packages, so I'd probably end up pulling it anyway.

So, to be honest, I'm not sure what to do about this...

**Comment by thomaslevesque** [comment]
Also, have you seen this?

https://stackoverflow.com/a/35462590/98713

**Comment by thomaslevesque** [comment]
Also, this: https://social.msdn.microsoft.com/Forums/windowsapps/en-US/2fa601f0-0b75-4920-8e99-ec880459673c/supported-api-test-failed-on-submitting-app-to-the-store-api-formatmessage-in#ee2f78ea-5dbe-4381-9b0d-1cad51dd8cdd

Apparently it was a known issue with the certification toolkit, which should be fixed now

**Comment by sonnemaf** [comment]
Creating a Release build before you make a Store package seems to work. I just successfully uploaded a new version to the store. You don't have to fix anything. Microsoft does.

**Comment by thomaslevesque** [comment]
Thanks @sonnemaf, closing this issue now.
