### ISSUE TITLE
How unsubscribe or Clean all handler?

### ISSUE THREAD

**Issue by pedoc** [thomaslevesque/WeakEvent#45]

**Comment by thomaslevesque** [comment]
Hi @pedoc,

There's no built-in way to do that, but you could just recreate the `WeakEventSource`.

**Comment by pedoc** [comment]
Thanks for the reply, and I want to discuss,Do you think it is necessary to add a similar api, such as'void UnsubscribeAll()', I can send a PR

**Comment by thomaslevesque** [comment]
Hi @pedoc,

Thanks for the suggestion, but to be honest, it's not something I'd like to see in the API. In all the event-like patterns that I've seen (C# events, Observable pattern in various languages, etc), there's never a way to remove all handlers, and for good reason. Each subscriber controls when it subscribes or unsubscribes; if something else unsubscribes it, it won't even know about it. It's more likely to cause bugs than anything else.

I'm not saying it never makes sense, but it's not a common scenario, and there's a reasonable workaround if you need to do it in your specific use case.

**Comment by pedoc** [comment]
I agree with this view, thank you 👍
